[package]
name = "rust-gpu-bridge"
version = "0.3.1"
edition = "2021"

[features]
default = []
glam = ["dep:glam"]
spirv-std = ["dep:spirv-std"]

[dependencies]
glam = { version = "0.23.0", optional = true }
spirv-std = { version = "0.6", optional = true }
